name: Dependency Updates

on:
  schedule:
    - cron: "0 10 * * 1" # Run at 10:00 UTC on Mondays
  workflow_dispatch: # Allow manual trigger

jobs:
  dependabot-updates:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pip-tools

      - name: Run pip-compile to update dependencies
        run: |
          mkdir -p .github/requirements
          cat pyproject.toml | grep -A 20 "dependencies" | grep -v "dependencies" | grep -v "\[" | sed 's/,$//' | sed 's/"//g' | sed 's/^[ \t]*//' > .github/requirements/requirements.in
          cat pyproject.toml | grep -A 20 "dev = \[" | grep -v "dev = \[" | grep -v "\]" | sed 's/,$//' | sed 's/"//g' | sed 's/^[ \t]*//' > .github/requirements/dev-requirements.in

          pip-compile --upgrade --output-file=.github/requirements/requirements.txt .github/requirements/requirements.in
          pip-compile --upgrade --output-file=.github/requirements/dev-requirements.txt .github/requirements/dev-requirements.in

      - name: Create Pull Request with updated dependencies
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update dependencies"
          title: "chore: update dependencies"
          body: |
            This PR updates project dependencies to their latest compatible versions.

            This is an automated PR created by the dependency update workflow.
          branch: dependency-updates
          base: main
